### ISSUE TITLE
how to run it?

### ISSUE THREAD

**Issue by xiatian111** [bpoteat/meteor-html5-video#1]
hi,Iam a novice For  meteor.but I'm very interested in this example.Can you introduce the steps to run  it?The more detailed, the better.very grateful.

**Comment by bpoteat** [comment]
If you haven't seen it, an overview of the application is here: http://www.artandlogic.com/blog/2014/03/recording-audio-video-with-html5-co-starring-meteor/

If you haven't already, install meteor and meteorite. A quick search will tell you everything you need to know about installing those so I'm not going into details about it.

Download or clone the project. In the terminal, go to the directory of the project folder. I tried running it without changing anything but it looks like a couple of packages need installing so do this:

> mrt add iron-router
> mrt add accounts-ui-bootstrap-dropdown

If you have any other packages missing, you'll need to make sure they are added as well.

Once those are installed, just run:

> mrt
> Stand back while Meteorite does its thing
> Done installing smart packages
> Ok, everything's ready. Here comes Meteor!
> [[[[[ ~/Downloads/meteor-html5-video-master ]]]]]

=> Started proxy.
=> Meteor 0.8.1.1 is available. Update this project with 'meteor update'.
=> Started MongoDB.  
=> Started your app.   

=> App running at: http://localhost:3000/

And there you go. As the app says, go to http://localhost:3000 to see the app. Create an account and go to record a video. It should be fairly easy to follow.

**Comment by isbkch** [comment]
Is there a way you update the code to run with last version of Meteor ? Once you do an meteor updatem you get lots of errors with iron-router and blaze templating

**Comment by Topol** [comment]
Getting following error when trying to run the app.

/Users/apple/.meteor/tools/f3947a4651/lib/node_modules/fibers/future.js:173
W20150216-01:57:32.756(5.5)? (STDERR)                       throw(ex);
W20150216-01:57:32.757(5.5)? (STDERR)                             ^
W20150216-01:57:32.802(5.5)? (STDERR) Error: A method named '/user-audios/insert' is already defined
W20150216-01:57:32.802(5.5)? (STDERR)     at packages/livedata/livedata_server.js:1258
W20150216-01:57:32.803(5.5)? (STDERR)     at Function._.each._.forEach (packages/underscore/underscore.js:113)
W20150216-01:57:32.803(5.5)? (STDERR)     at _.extend.methods (packages/livedata/livedata_server.js:1256)
W20150216-01:57:32.804(5.5)? (STDERR)     at Meteor.Collection._defineMutationMethods (packages/mongo-livedata/collection.js:676)
W20150216-01:57:32.804(5.5)? (STDERR)     at new Meteor.Collection (packages/mongo-livedata/collection.js:173)
W20150216-01:57:32.804(5.5)? (STDERR)     at app/lib/models.js:20:14
W20150216-01:57:32.804(5.5)? (STDERR)     at app/lib/models.js:34:3
W20150216-01:57:32.805(5.5)? (STDERR)     at /Users/apple/Desktop/meteor-html5-video/.meteor/local/build/programs/server/boot.js:155:10
W20150216-01:57:32.807(5.5)? (STDERR)     at Array.forEach (native)
W20150216-01:57:32.808(5.5)? (STDERR)     at Function._.each._.forEach (/Users/apple/.meteor/tools/f3947a4651/lib/node_modules/underscore/underscore.js:79:11)
